### ISSUE TITLE
How to use the logger to automatically log to slack

### ISSUE THREAD

**Issue by Tob0t** [adityadarma/adonis-logger-slack#1]
Thanks for the contribution to adonisjs ecosystem.
I just tried out the logger, and it works out-of-the-box for exception handling 🥳 

However, what I did not get yet or probably set up wrong is the following:

What I did so far:
`logger.ts`
```
default: 'slack',
slack: {
      enabled: true,
      name: env.get('APP_NAME'),
      level: env.get('LOG_LEVEL', 'info'),
      icon: 'boom',
      url: env.get('LOG_SLACK_WEBHOOK_URL'),
      transport: {
        targets: targets()
          .pushIf(!app.inProduction, targets.pretty())
          .pushIf(app.inProduction, targets.file({ destination: 1 }))
          .toArray(),
      },
    },
```
I want to send it automatically to slack when I write somewhere in the code `logger.error('New error')`, however, it is just logged in the console but not sent to slack?
Am I doing something wrong?

**Comment by adityadarma** [comment]
hey @Tob0t , I have updated the documentation, please check again

**Comment by Tob0t** [comment]
Cool thanks a lot, now it works 👍
